project:
  type: website

website:
  title: "Global Temperature Anomalies"
  description: "Data compilation for global temperature anomalies."
  navbar:
    background: secondary
    search: false
    tools:
      - icon: file-earmark-code
        href: https://everval.github.io/Odds-of-breaching-1.5C/
        text: Article
      - icon: person-gear
        href: https://everval.github.io/
        text: Author
  repo-url: https://github.com/everval/Global-Temperature-Anomalies
  repo-actions: [source, issue]


format:
  html:
    mainfont: Georgia, serif
    html-math-method: katex
    theme: litera
    toc: true