project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    mainfont: Georgia, serif
    html-math-method: katex
    theme: litera
    toc: true
  typst:
    font: "Computer Modern"
    section-numbering: 1.1.1
    paper: a4
    numbering: true
    margin:
      x: 2cm
      y: 2cm
    include-before-body:
      - text: |
          #set par(justify: true)

engine: julia
execute: 
  enabled: false
  cache: true
  freeze: auto