project:
  type: website

website:
  title: "Global Temperature Anomalies in Practice"
  description: "An Open, Reproducible Framework for Global Temperature Anomalies Baseline Harmonisation and ENSO-Aware Visualisation"
  navbar:
    background: secondary
    search: false
    tools:
      - icon: file-earmark-code
        href: https://github.com/everval/Global-Temperature-Anomalies/blob/main/script.jl
        text: Article
      - icon: person-gear
        href: https://everval.github.io/
        text: Author
  repo-url: https://github.com/everval/Global-Temperature-Anomalies
  repo-actions: [source, issue]
  page-footer: "Page created by [J. Eduardo Vera-Valdés](https://everval.github.io/)."

format:
  html:
    mainfont: Georgia, serif
    html-math-method: katex
    theme: litera
    toc: true
    grid:
      body-width: 1100px
  typst:
    font: "Computer Modern"
    section-numbering: 1.1.1
    paper: a4
    numbering: true
    margin:
      x: 2cm
      y: 2cm
    include-before-body:
      - text: |
          #set par(justify: true)